-- V1.2__Add_Posting_Audit_Columns.sql

ALTER TABLE posting
    ADD COLUMN updated_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN updated_by VARCHAR(50) NOT NULL DEFAULT '';
